"""Crear tabla maestros

Revision ID: 464c1f17b002
Revises: 9414b6f0007e
Create Date: 2026-03-02 17:47:20.380844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464c1f17b002'
down_revision = '9414b6f0007e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maestro',
    sa.Column('matricula', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('apellidos', sa.String(length=50), nullable=True),
    sa.Column('especialidad', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('matricula')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maestro')
    # ### end Alembic commands ###
